name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main # replace with your branch name
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Jekyll site
        uses: helaili/jekyll-action@v2.7.3
        with:
          jekyll-version: '4.3.2'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
