name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - main # replace with the name of your source code branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'
          
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          
          
      - name: Build and deploy
        env:
          JEKYLL_ENV: production
        run: |
          /vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.2 build
          git config --global user.name khurshiduktamov
          git config --global user.email khurshiduktamov@users.noreply.github.com
          cd _site && git init
          git remote add origin https://github.com/khurshiduktamov/khurshiduktamov.github.io.git # replace <username> with your GitHub username
          git add .
          git commit -m "Deployed via GitHub Actions"
          git push -f origin master:gh-pages
